-- Add up migration script here

-- Mock data generated by ChatGPT
INSERT INTO `Item` (`Name`, `Price`, `IsAvailable`, `Description`, `StoreId`) VALUES
-- Store 1 (Chinese)
('Sweet and Sour Pork', 12.50, TRUE, 'Classic Cantonese stir‑fry with pineapple.', 1),
('Beef Chow Fun', 10.00, TRUE, 'Flat rice noodles with beef and soy sauce.', 1),

-- Store 2 (Malay)
('Nasi Lemak', 8.00, TRUE, 'Rice cooked in coconut milk with sambal.', 2),
('Mee Rebus', 7.50, FALSE, 'Yellow noodles in spicy sweet potato gravy.', 2),

-- Store 3 (Indian)
('Chicken Tikka Masala', 11.00, TRUE, 'Grilled tikka chicken in creamy tomato sauce.', 3),
('Mutton Biryani', 13.50, FALSE, 'Aromatic biryani with spiced mutton.', 3),

-- Store 4 (Peranakan)
('Ayam Buah Keluak', 14.00, TRUE, 'Peranakan chicken with black nuts.', 4),
('Nyonya Laksa', 9.50, TRUE, 'Spicy coconut noodle soup with prawns.', 4),

-- Store 5 (Western)
('Ribeye Steak', 22.00, TRUE, 'Grilled ribeye with garlic butter.', 5),
('Spaghetti Carbonara', 15.00, FALSE, 'Pasta with pancetta and creamy sauce.', 5),

-- Store 6 (Japanese)
('Salmon Sashimi', 18.00, TRUE, 'Fresh sliced salmon sashimi.', 6),
('Tonkotsu Ramen', 13.00, TRUE, 'Rich pork bone broth ramen.', 6),

-- Store 7 (Chinese)
('Mapo Tofu', 9.00, TRUE, 'Spicy Szechuan tofu with minced pork.', 7),
('Peking Duck Wrap', 16.00, FALSE, 'Roast duck slices in pancake.', 7),

-- Store 8 (Malay)
('Rendang Daging', 12.00, TRUE, 'Slow‑cooked beef in coconut spices.', 8),
('Kuih Seri Muka', 4.50, TRUE, 'Layered glutinous rice cake dessert.', 8),

-- Store 9 (Indian)
('Fish Curry', 11.50, FALSE, 'Tangy fish curry with tamarind.', 9),
('Garlic Naan', 3.50, TRUE, 'Oven‑baked garlic flatbread.', 9),

-- Store 10 (Peranakan)
('Ulak Laksa', 10.50, TRUE, 'Spicy noodle soup with fishballs.', 10),
('Kueh Pie Tee', 6.00, TRUE, 'Crispy tart shells with shrimp.', 10),

-- Store 11 (Western)
('BBQ Ribs', 19.00, TRUE, 'Slow‑cooked ribs with BBQ sauce.', 11),
('Caesar Salad', 9.00, TRUE, 'Romaine lettuce with creamy dressing.', 11),

-- Store 12 (Japanese)
('Unagi Don', 16.50, TRUE, 'Grilled eel over rice bowl.', 12),
('Chicken Katsu Curry', 12.00, FALSE, 'Breaded chicken with Japanese curry.', 12),

-- Store 13 (Chinese)
('Char Siew Rice', 8.50, TRUE, 'Roast pork over rice.', 13),
('Wonton Soup', 7.00, TRUE, 'Shrimp wontons in clear broth.', 13),

-- Store 14 (Malay)
('Laksa Lemak', 9.50, TRUE, 'Coconut laksa with prawns.', 14),
('Roti Jala', 5.00, FALSE, 'Lace pancakes with curry dip.', 14),

-- Store 15 (Indian)
('Butter Chicken', 12.50, TRUE, 'Creamy tomato chicken curry.', 15),
('Dosa Masala', 7.00, TRUE, 'Crispy rice pancake with potato masala.', 15),

-- Store 16 (Peranakan)
('Putu Mayam', 5.50, TRUE, 'String hoppers with coconut sugar.', 16),
('Ikan Assam Pedas', 13.00, FALSE, 'Spicy sour fish stew.', 16),

-- Store 17 (Western)
('Grilled Salmon', 18.50, TRUE, 'Salmon fillet with lemon butter.', 17),
('Mac & Cheese', 8.00, TRUE, 'Creamy baked macaroni and cheese.', 17),

-- Store 18 (Japanese)
('Tempura Udon', 11.00, TRUE, 'Udon noodles with shrimp tempura.', 18),
('Matcha Ice Cream', 4.50, TRUE, 'Green tea flavored ice cream.', 18),

-- Store 19 (Chinese)
('Steamed Fish', 15.00, TRUE, 'Whole fish with ginger and soy.', 19),
('Egg Fried Rice', 6.00, TRUE, 'Classic fried rice with egg.', 19),

-- Store 20 (Malay)
('Soto Ayam', 7.50, FALSE, 'Chicken soup with turmeric and noodles.', 20),
('Apam Balik', 4.00, TRUE, 'Folded pancake with peanuts.', 20),

-- Store 21 (Indian)
('Paneer Tikka', 10.00, TRUE, 'Grilled marinated cottage cheese.', 21),
('Masala Chai', 3.00, TRUE, 'Spiced Indian milk tea.', 21),

-- Store 22 (Peranakan)
('Kueh Lapis', 6.00, TRUE, 'Layered spice cake.', 22),
('Prawn Assam Chili', 14.00, FALSE, 'Prawns in spicy tamarind sauce.', 22),

-- Store 23 (Western)
('Club Sandwich', 8.50, TRUE, 'Triple‑decker sandwich with bacon.', 23),
('Tomato Soup', 5.00, TRUE, 'Creamy tomato basil soup.', 23),

-- Store 24 (Japanese)
('Yakitori Skewers', 9.00, TRUE, 'Grilled chicken skewers with sauce.', 24),
('Chawanmushi', 5.50, TRUE, 'Savory steamed egg custard.', 24),

-- Store 25 (Chinese)
('Spring Rolls', 5.00, TRUE, 'Crispy vegetable rolls.', 25),
('Kung Pao Chicken', 11.00, FALSE, 'Spicy chicken stir‑fry with peanuts.', 25),

-- Store 26 (Malay)
('Cendol', 4.50, TRUE, 'Icy dessert with coconut and palm sugar.', 26),
('Beef Rendang', 12.00, TRUE, 'Rich slow‑cooked beef curry.', 26),

-- Store 27 (Indian)
('Aloo Gobi', 9.00, TRUE, 'Potato and cauliflower dry curry.', 27),
('Idli Sambar', 6.50, TRUE, 'Steamed rice cakes with lentil soup.', 27),

-- Store 28 (Peranakan)
('Kueh Salat', 5.50, TRUE, 'Pandan custard on rice cake.', 28),
('Laksa Kari', 10.00, FALSE, 'Spicy coconut noodle soup.', 28),

-- Store 29 (Western)
('Fish & Chips', 10.50, TRUE, 'Battered fish with fries.', 29),
('Quiche Lorraine', 7.00, TRUE, 'Savory tart with bacon & cheese.', 29),

-- Store 30 (Japanese)
('Soba Noodles', 9.50, TRUE, 'Cold buckwheat soba with dipping sauce.', 30),
('Gyoza', 6.00, TRUE, 'Pan‑fried dumplings.', 30),

-- Store 31 (Chinese)
('Hot and Sour Soup', 6.00, TRUE, 'Spicy and tangy broth.', 31),
('Char Kway Teow', 8.00, TRUE, 'Fried flat noodles with char.' , 31),

-- Store 32 (Malay)
('Ikan Bakar', 11.00, FALSE, 'Grilled fish with chili paste.', 32),
('Pulut Hitam', 4.00, TRUE, 'Black glutinous rice dessert.', 32),

-- Store 33 (Indian)
('Chicken 65', 9.50, TRUE, 'Fried spicy chicken bite.', 33),
('Rasam', 3.50, TRUE, 'Tangy South Indian soup.', 33),

-- Store 34 (Peranakan)
('Laksa Sarawak', 11.00, TRUE, 'Spicy Sarawak laksa.', 34),
('Otak‑Otak', 6.50, FALSE, 'Grilled fish cake in banana leaf.', 34),

-- Store 35 (Western)
('Chicken Alfredo', 12.50, TRUE, 'Fettuccine with creamy alfredo sauce.', 35),
('Greek Salad', 8.00, TRUE, 'Salad with feta, olives, cucumber.', 35),

-- Store 36 (Japanese)
('Onigiri', 3.00, TRUE, 'Rice ball with filling.', 36),
('Miso Soup', 2.50, TRUE, 'Traditional soybean miso soup.', 36);