-- Add up migration script here

-- Nomer table
CREATE TABLE IF NOT EXISTS `Nomer` (
    `Id` INTEGER PRIMARY KEY AUTO_INCREMENT,
    `DisplayName` VARCHAR(100) NOT NULL UNIQUE,
    `Email` VARCHAR(100) NOT NULL UNIQUE,
    `PasswordHash` VARCHAR(100) NOT NULL UNIQUE,
    `UpdatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);