-- Add up migration script here

-- Mock data generated by ChatGPT
INSERT INTO `Store` (`Name`, `IsOpen`, `Cuisine`, `Description`, `LocationId`) VALUES
-- Location 1
('Golden Wok Chinese', TRUE, 'Chinese', 'Authentic Chinese dishes with wok hei flavors.', 1),
('Nasi Lemak House', TRUE, 'Malay', 'Serving fragrant nasi lemak with sambal.', 1),
('Spice Route Indian', FALSE, 'Indian', 'Rich and flavorful North and South Indian dishes.', 1),
('Peranakan Heritage Kitchen', TRUE, 'Peranakan', 'Classic Nyonya dishes with rich heritage.', 1),
('Western Grill & Pasta', TRUE, 'Western', 'Grilled meats and classic pasta dishes.', 1),
('Tokyo Ramen House', FALSE, 'Japanese', 'Authentic ramen with rich broths.', 1),

-- Location 2
('Dim Sum Paradise', TRUE, 'Chinese', 'Steamed and fried dim sum specialties.', 2),
('Satay Corner', FALSE, 'Malay', 'Grilled satay skewers with peanut sauce.', 2),
('Roti Prata Hub', TRUE, 'Indian', 'Freshly made roti prata and curries.', 2),
('Baba Nyonya Flavours', TRUE, 'Peranakan', 'Fusion of Chinese and Malay culinary traditions.', 2),
('The Burger Joint', FALSE, 'Western', 'Gourmet burgers with local twists.', 2),
('Sakura Sushi Bar', TRUE, 'Japanese', 'Fresh sushi and sashimi prepared daily.', 2),

-- Location 3
('Spicy Szechuan Delights', TRUE, 'Chinese', 'Bold and spicy Szechuan cuisine.', 3),
('Kampong Malay Kitchen', TRUE, 'Malay', 'Traditional Malay recipes and vibrant spices.', 3),
('Banana Leaf Biryani', FALSE, 'Indian', 'Authentic biryani served on banana leaves.', 3),
('Little Nyonya Cafe', TRUE, 'Peranakan', 'Home-style Peranakan cooking and desserts.', 3),
('Steakhouse 81', TRUE, 'Western', 'Premium cuts and hearty Western meals.', 3),
('Okonomiyaki Street', FALSE, 'Japanese', 'Savory Japanese pancakes and street food.', 3),

-- Location 4
('Wok Master', TRUE, 'Chinese', 'Homestyle stir-fried dishes with wok hei.', 4),
('Seri Melayu Delights', FALSE, 'Malay', 'Delicious kampong-style Malay food.', 4),
('Curry Express', TRUE, 'Indian', 'Quick and flavorful Indian curries.', 4),
('Nyonya Street Eats', TRUE, 'Peranakan', 'Peranakan street food classics.', 4),
('Urban Western Bites', FALSE, 'Western', 'Trendy Western meals and quick bites.', 4),
('Sushi Zen', TRUE, 'Japanese', 'Elegant sushi platters and bento sets.', 4),

-- Location 5
('Canton Garden', TRUE, 'Chinese', 'Traditional Cantonese dishes and soups.', 5),
('Ayam Penyet King', TRUE, 'Malay', 'Crispy smashed chicken with sambal.', 5),
('Tandoori Flame', FALSE, 'Indian', 'Authentic tandoori grilled specialties.', 5),
('Baba’s Kitchen', TRUE, 'Peranakan', 'Family-style Nyonya cooking.', 5),
('Grillhouse 21', TRUE, 'Western', 'Casual grilled favorites and sandwiches.', 5),
('Ramen Ichiban', FALSE, 'Japanese', 'Classic ramen with a modern twist.', 5),

-- Location 6
('Dragon’s Gate', TRUE, 'Chinese', 'Specialty dim sum and roast meats.', 6),
('Nasi Padang Express', TRUE, 'Malay', 'Variety of nasi padang dishes.', 6),
('Masala Haven', FALSE, 'Indian', 'A haven for lovers of Indian spices.', 6),
('Peranakan Family Table', TRUE, 'Peranakan', 'Comforting Nyonya family recipes.', 6),
('Western Diner Co.', TRUE, 'Western', 'All-day brunch and Western classics.', 6),
('Yokohama Sushi House', FALSE, 'Japanese', 'Freshly prepared sushi and donburi.', 6);