-- Add up migration script here

-- Location table
CREATE TABLE IF NOT EXISTS `Location` (
    `Id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Name` VARCHAR(255) NOT NULL UNIQUE,
    `Latitude` REAL NOT NULL,
    `Longitude` REAL NOT NULL
);

-- Store table
CREATE TABLE IF NOT EXISTS `Store` (
    `Id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Name` VARCHAR(255) NOT NULL UNIQUE,
    `IsOpen` BOOLEAN NOT NULL,
    `Cuisine` VARCHAR(255) NOT NULL,
    `Description` VARCHAR(255) NOT NULL,
    `LocationId` INTEGER NOT NULL,
    FOREIGN KEY (`LocationId`) REFERENCES `Location`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Item table
CREATE TABLE IF NOT EXISTS `Item` (
    `Id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Name` VARCHAR(255) NOT NULL,
    `Price` REAL NOT NULL,
    `IsAvailable` BOOLEAN NOT NULL,
    `Description` VARCHAR(255) NOT NULL,
    `StoreId` INTEGER NOT NULL,
    FOREIGN KEY (`StoreId`) REFERENCES `Store`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Review table
CREATE TABLE IF NOT EXISTS `Review` (
    `Id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Score` INTEGER NOT NULL CHECK (`Score` >= 1 AND `Score` <= 5),
    `Comment` VARCHAR(255) NOT NULL,
    `NomerId` INTEGER NOT NULL,
    `StoreId` INTEGER NOT NULL,
    FOREIGN KEY (`NomerId`) REFERENCES `Nomer`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`StoreId`) REFERENCES `Store`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE
);